theme = "yellowed"

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
g = { a = "code_action" }
esc = ["collapse_selection", "keep_primary_selection"]
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

[keys.normal.space]
w = ":write"
q = ":quit"

[editor]
auto-save = true
line-number = "relative"
auto-format = true
true-color = true

[editor.lsp]
display-messages = true

[editor.whitespace]
render = "none"
[editor.indent-guides]
render = false
