[[language]]
name = "c"
language-id = "c"
scope = "source.c"
auto-format = true
comment-token = "//"
indent = { tab-width = 4, unit = "  " }
file-types = ["c", "h"]

[language-server.c]
command = "clangd"

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "rust"
auto-format = true

